In [1]:
import numpy as np
import matplotlib.pyplot as plt

from train.davis2017_dataset import get_trainval
from train import viz

DATA_DIR = 'G:\\Team Drives\\COML-Fall-2018\\T0-VidSeg\\Data\\DAVIS'

davis = get_trainval(DATA_DIR)

In [26]:
next_choice = np.random.choice(davis.num_images)

img = davis.load_image(next_choice).astype(np.float32) / 255
mask = davis.load_mask(next_choice)[0][..., 0].astype(np.uint8) * 255
print(img)
plt.imshow(img)
plt.show()

[[[0.94509804 0.94509804 0.94509804]
  [0.98039216 0.98039216 0.98039216]
  [1.         1.         1.        ]
  ...
  [0.47058824 0.47058824 0.47843137]
  [0.6        0.6156863  0.61960787]
  [0.45882353 0.48235294 0.48235294]]

 [[0.9882353  0.9882353  0.9882353 ]
  [0.98039216 0.98039216 0.98039216]
  [1.         1.         1.        ]
  ...
  [0.62352943 0.62352943 0.6313726 ]
  [0.6745098  0.6901961  0.69411767]
  [0.5176471  0.5411765  0.5411765 ]]

 [[1.         1.         1.        ]
  [0.9843137  0.9843137  0.9843137 ]
  [1.         1.         1.        ]
  ...
  [0.7176471  0.70980394 0.72156864]
  [0.72156864 0.7254902  0.73333335]
  [0.5058824  0.52156866 0.5254902 ]]

 ...

 [[0.49803922 0.5254902  0.4627451 ]
  [0.49019608 0.5176471  0.44705883]
  [0.48235294 0.50980395 0.4392157 ]
  ...
  [0.3882353  0.45490196 0.32941177]
  [0.38431373 0.4509804  0.3254902 ]
  [0.3882353  0.45490196 0.32156864]]

 [[0.45882353 0.4862745  0.41568628]
  [0.4627451  0.49019608 0.41960785]


ValueError: 3-dimensional arrays must be of dtype unsigned byte, unsigned short, float32 or float64